name: tm1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  
  # State Management yang diminta modul 
  flutter_riverpod: ^2.6.1 

  # Library untuk mengambil data dari API (Tugas No. 2) [cite: 66, 69]
  http: ^1.2.2

  # Library untuk mengambil data dari API (Tugas No. 7) [cite: 61, 482]
  dio: ^5.4.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true